# Generated by Django 3.2.4 on 2021-06-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownlodedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('download_time', models.DateTimeField(verbose_name='date downloaded')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
